import Head from 'next/head'
import { Radio } from 'antd'
import OneRoomEstimation from './OneRoomEstimation'
import TwoRoomEstimation from './TwoRoomEstimation'
import TwoBhkEstimation from './TwoBhkEstimation'
import { useState } from 'react'



export default function Home() {

const [oneRoomEstimation, setOneRoomEstimation] = useState(true)
const [twoRoomEstimation, setTwoRoomEstimation] = useState(false)
const [upcoming, setUpcoming] = useState(false)
const [twoBHK, setTwoBHK] = useState(false)

  return (
    <>
      <Head>
        <title>Construction Estimator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>

    <section className='homePage'>
      <div className='header'>
      <h1 className='title'>Construction Estimator</h1>
      </div>
     
      <video className='videoBg' src="/bg.mp4" autoPlay={true} loop={true} muted={true} controls={false} ></video>
      
      <div className="background-video">
      <video autoPlay loop muted playsInline>
        <source src={"/background.mp4"} type="video/mp4" />
      </video>
    </div>

<p>Select the Structure element you want to estimate</p>
      <Radio.Group buttonStyle="solid" defaultValue={'a'} >
      <Radio.Button  value={'a'} onChange={(e)=>{
        setOneRoomEstimation(true)
setTwoRoomEstimation(false)
setTwoBHK(false)
setUpcoming(false)
      }}>One Room</Radio.Button>
      <Radio.Button value={'b'} onChange={(e)=>{
        setOneRoomEstimation(false)
setTwoRoomEstimation(true)
setUpcoming(false)
setTwoBHK(false)
      }}>Two Rooms</Radio.Button>

<Radio.Button value={'c'} onChange={(e)=>{
        setOneRoomEstimation(false)
setTwoRoomEstimation(false)
setUpcoming(false)
setTwoBHK(true)
      }}>2BHK </Radio.Button>


      <Radio.Button value={'d'} onChange={(e)=>{
        setOneRoomEstimation(false)
setTwoRoomEstimation(false)
setUpcoming(true)
setTwoBHK(false)
      }}>Upcoming</Radio.Button>
</Radio.Group>
     {/* <MaterialDropdown/> */}
{
  oneRoomEstimation && <OneRoomEstimation/>
}

{
  twoRoomEstimation && <TwoRoomEstimation/>
}

{
  twoBHK && <TwoBhkEstimation/>
}

{
  upcoming ? <><h2>Multi rooms and Multi storey structure estimation</h2>
  <p>Coming Soon...!</p>
  </>:<></>
}

</section>

      </main>
    </>
  )
}
